### ISSUE TITLE
Preparing submission file for multiome data

### ISSUE THREAD

**Issue by Yohana-Berhe** [DendrouLab/panpipes#124]
I am running a multiome data and preparing my submission file for the ingest workflow. Specifying the cellranger 'outs' folder as a x_path and 'cellranger' as x_filetype results in an error. However, specifying the complete path i.e 'outs/flitered_feature_bc_matrix.h5' and filetype '10X_h5' solves the issue.

**Comment by bio-la** [comment]
thanks for finding this issue! i will check the code and include an example sample file in a new tutorial!

**Comment by bio-la** [comment]
this issue is now fixed in PR #130 and merged in main. please update the panpipes code by pulling and installing the latest version of panpipes from github!
clarifications are provided on [`setup_for_ingest.html`](https://panpipes-pipelines.readthedocs.io/en/latest/usage/setup_for_qc_mm.html)  and examples are provided in a tutorial  and sample files in the resources folder. please wait for the website to update to reflect latest changes, but you can find the documentation also on github https://github.com/DendrouLab/panpipes/blob/main/docs/usage/setup_for_qc_mm.md
