### ISSUE TITLE
Change path in yaml for ingestion tutorial

### ISSUE THREAD

**Issue by kevinrue** [DendrouLab/panpipes#163]
The pipeline.yml provided in the tutorial includes a path that doesn’t play well with the tutorial. 

You probably want to change `panpipes-tutorials/tutorials/ingesting_data/qc_genelist_1.0.csv` to `qc_genelist_1.0.csv`.

For example, see the GitHub action workflow which uses ‘sed’ to change that file path https://github.com/DendrouLab/panpipes/blob/kra-gha/.github/workflows/ingestion-ci.yml#L88

**Comment by giuliaelgarcia** [comment]
Personally, I don't think that changing it to qc_genelist_1.0.csv will help since it assumes that the file is in your current directory, which for example my case wasn't. I think the way to go around it (especially for new users) would be to make it clear in the tutorials that each user will have to adapt the yml to the correct path based on their own setup. Since this has to be done all throughout the various tutorials.

**Comment by kevinrue** [comment]
I'm confused. Why would it assume that it's in the current directory if the `pipeline.yml` declares a path to another directory?

**Comment by kevinrue** [comment]
Side note: the tutorial generally does a good job of indicating bits that need to be adjusted by users. However, this is the only place in the whole tutorial where the example file is not immediately usable as is. All the other example files contain values that point to the place where the tutorial files are located/downloaded.
