### ISSUE TITLE
Support for Nvidia GPUs

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#204]
After installation using pip of the latest version of panpipes, when running integration step, the scvi falls back on CPU even if running on CPU thread, because of lack of jax. Running `pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` as suggested [here](https://jax.readthedocs.io/en/latest/installation.html) solved the problem.

**Comment by wlason** [comment]
I did clone and install yesterday and the issue was still there, in the ran_scvi.log:
INFO - raw counts found in layer
INFO - Unable to initialize backend 'cuda': 
INFO - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
WARNING - An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

I did see in scvi-tools [documentation](https://docs.scvi-tools.org/en/stable/installation.html) they suggest running
`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`
`conda install jax jaxlib -c conda-forge`
in addition to installing scvi, so it may be an alternative to my original solution.

**Comment by bio-la** [comment]
@Zethson could you please pass this on to the scvi team?

**Comment by bio-la** [comment]
we have reinstated jax as the first installed dependency, however i can't guarantee that the order of installation will effectively ensure that the GPU is recognised. we'll do further testing, and add info in the installation to warn the users of this behaviour (which is not due to panpipe), which can be solved with the additional installation step as you mentioned. thanks for reporting @wlason !
