### ISSUE TITLE
1st Experience: Preprocessing, Integration, Clustering 

### ISSUE THREAD

**Issue by SarahOuologuem** [DendrouLab/panpipes#45]
Hi, 

again just a few little things I ran into while running the steps Preprocessing, Integration, and Clustering. 

- Preprocessing: 
	- Specifying the parameter "output_logged_mudata" in the pipeline.yml did not work for me, it threw an error. But in the pipeline.yml it is stated as "TODO" that this parameter is supposed to go, so I guessed that this error isn't so important. When leaving this parameter empty, the preprocessing worked completely fine  
	
- Integration: 
	- Running "panpipes integration make plot_pcas --local" resulted in an error, stating: 
		"Target task 'plot_pcas' is not a pipelined task in Ruffus. Is it spelt correctly ?"
	
- Clustering: 
	- So that others don't experience the same error, it may be helpful to mention that one needs to specify more than one resolution, otherwise clustree throws an error: 
		"Error: Less than two column names matched the prefix: leiden_re
    Execution halted"

Best, 
Sarah

**Comment by crichgriffin** [comment]
Thanks Sarah,

Preprocess: 
Did you specify a True/False value here or a path? I believe it is supposed to be a path. But also you are correct that we don't intend to maintain that functionality. Since we are utilising scanpy layers instead. 

Integration:
You are correct that "plot_pcas" does not exist as a task. You can always work out what the tasks are called by running `panpipes integration show full`. I would expect the pcas to be plotted in the preprocess step, did they not plot?


Clustering:
I have referenced the clustree issue in the yml, and in the documentation on the website. https://panpipes-pipelines.readthedocs.io/en/latest/workflows/clustering.html

**Comment by crichgriffin** [comment]
I will leave this open to remind myself to remove the "output_logged_mudata" parameter

**Comment by SarahOuologuem** [comment]
Thank you!
Regarding the integration, I ran _panpipes integration make plot_pcas --local_ because it is still mentioned in the README.md: https://github.com/DendrouLab/panpipes/blob/main/README.md, namely: _2. Run panpipes integration make plot_pcas and assess the post filtering qc plots, and pca outputs_
But yes, the PCA is plotted in the preprocess step

**Comment by crichgriffin** [comment]
Great! I will change the README. I'm hopeful that people will start using
the website over the github. But its important to have it be correct anyway!
