### ISSUE TITLE
Clustree plot won't render if ggraph package not updated

### ISSUE THREAD

**Issue by JHYSiu** [DendrouLab/panpipes#89]
I got this error when running clustree: Error in check.length(gparname) : 'gpar' element 'lwd' must not be length 0

Solution: R package ggraph must be 2.1.0 (it won't work if ggraph is 2.0.5)

**Comment by crichgriffin** [comment]
Did you install using the conda instructions or the python venv?

**Comment by crichgriffin** [comment]
fixed in #96

**Comment by bio-la** [comment]
I also can't replicate the issue, and i have the versions pinned in the
installation.


Il giorno mer 6 set 2023 alle ore 21:44 Charlotte Rich-Griffin <
***@***.***> ha scritto:

**Comment by deevdevil88** [comment]
This might be to do with BMRC R module specifically? Because , we have been using the python venv installation route in general in the group so far. But weirdly enough I don't have this issue, but then again the R module I use has lots of packages installed like Seurat etc, so maybe ggraph got updated

**Comment by crichgriffin** [comment]
I have updated the python venv R installation script. So now it better matches the conda instructions, PR is #96
